[theme]
primaryColor = "#044A30"
backgroundColor = "#C2DFD4"
secondaryBackgroundColor = "#A8CFBE"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
